name: CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
